//
// Created by User on 10/4/2026.
//

#ifndef C_PROJECT_02_ENGINEERING_CALCULATOR_ARITHMETICMENU_H
#define C_PROJECT_02_ENGINEERING_CALCULATOR_ARITHMETICMENU_H

void arithmeticMenu(void);

#endif //C_PROJECT_02_ENGINEERING_CALCULATOR_ARITHMETICMENU_H
