//
// Created by User on 10/4/2026.
//

#ifndef C_PROJECT_02_ENGINEERING_CALCULATOR_INTEGERMNU_H
#define C_PROJECT_02_ENGINEERING_CALCULATOR_INTEGERMNU_H

void integerMenu(void);

#endif //C_PROJECT_02_ENGINEERING_CALCULATOR_INTEGERMNU_H
