//
// Created by morro on 10/4/2026.
//

#ifndef C_PROJECT_02_ENGINEERING_CALCULATOR_POWERSANDROOTSMENU_H
#define C_PROJECT_02_ENGINEERING_CALCULATOR_POWERSANDROOTSMENU_H

void powersAndRootsMenu(void);

#endif //C_PROJECT_02_ENGINEERING_CALCULATOR_POWERSANDROOTSMENU_H
