//
// Created by User on 10/4/2026.
//

#ifndef C_PROJECT_02_ENGINEERING_CALCULATOR_STARTMENU_H
#define C_PROJECT_02_ENGINEERING_CALCULATOR_STARTMENU_H

void startMenu(void);

#endif //C_PROJECT_02_ENGINEERING_CALCULATOR_STARTMENU_H
